# Generated by Django 5.0 on 2024-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_service_remove_booking_business_remove_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
