# Generated by Django 5.0 on 2024-03-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_date_booked_alter_booking_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
    ]
