# Generated by Django 5.0 on 2024-03-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_booked',
        ),
    ]
